Description: >-
    Ec2 stack
    Reference:
    https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-ec2.html
Parameters:
  OwnerName:
    Type: String
    Description: An arbitrary tag name for the owner of these resources

  ProjectName:
    Type: String
    Description: The Project name to which these resources belong to

  Environment:
    Type: String
    Default: dev
    Description: Environment name to append to resources names and tags

  KeyName:
    Type: String
    Description: Key Name to connect to Ec2 instance

  VpcId:
    Type: String
    Description: VPC used to deploy Ec2

  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t1.micro
      - t2.micro
      - t2.small
      - t2.medium
      - m3.medium
      - m3.large
      - m3.xlarge
      - m3.2xlarge
    ConstraintDescription: must be a valid EC2 instance type.

  SubnetId:
    Type: String
    Description: Subnet to deploy Ec2
  
  SecurityGroupServer:
    Type: String
    Description: Security group for server

  DBAddress:
    Type: String
    Description: Database endpoint

  DBName:
    Type: String
    Description: Database name

  DbUser:
    Type: String
    Description: Name of Mysql Admin
  
  DbPass:
    Type: String
    Description: Password of Mysql Admin

Mappings:
  AWSInstanceType2Arch:
    t1.micro:
      Arch: PV64
    t2.micro:
      Arch: HVM64
    t2.small:
      Arch: HVM64
    t2.medium:
      Arch: HVM64
    m3.medium:
      Arch: PV64
    m3.large:
      Arch: PV64
    m3.xlarge:
      Arch: PV64
    m3.2xlarge:
      Arch: PV64
  AWSRegionArch2AMI:
    us-east-1:
      PV64: ami-7c807d14
      HVM64: ami-76817c1e
    us-west-2:
      PV64: ami-1b3b462b
      HVM64: ami-d13845e1
    us-west-1:
      PV64: ami-a8d3d4ed
      HVM64: ami-f0d3d4b5
    eu-west-1:
      PV64: ami-672ce210
      HVM64: ami-892fe1fe
    ap-southeast-1:
      PV64: ami-56b7eb04
      HVM64: ami-a6b6eaf4
    ap-northeast-1:
      PV64: ami-25dd9324
      HVM64: ami-29dc9228
    ap-southeast-2:
      PV64: ami-6bf99c51
      HVM64: ami-d9fe9be3
    sa-east-1:
      PV64: ami-c7e649da
      HVM64: ami-c9e649d4
    us-gov-west-1:
      PV64: ami-ab4a2d88
      HVM64: ami-a54a2d86
    cn-north-1:
      PV64: ami-cab82af3
      HVM64: ami-ccb82af5

Resources: 
  EC2Instance:
    Type: AWS::EC2::Instance
    Metadata:
      'AWS::CloudFormation::Init':
        config:
          packages:
            yum:
              httpd: []
              php: []
              php-mysql: []
          sources:
            /var/www/html: 'http://wordpress.org/wordpress-5.1.1.tar.gz'
          files:
            /var/www/html/wordpress/wp-config.php:
              content: !Join 
                - ''
                - - |
                    <?php
                  - 'define(''DB_NAME'',          '''
                  - !Ref DBName
                  - |
                    ');
                  - 'define(''DB_USER'',          '''
                  - !Ref DbUser
                  - |
                    ');
                  - 'define(''DB_PASSWORD'',      '''
                  - !Ref DbPass
                  - |
                    ');
                  - 'define(''DB_HOST'',          '''
                  - !Ref DBAddress
                  - |
                    ');
                  - |
                    define('DB_CHARSET',       'utf8');
                  - |
                    define('DB_COLLATE',       '');
                  - |
                    $table_prefix = 'wp_';
                  - |
                    require_once( ABSPATH . 'wp-settings.php' );
              mode: '000644'
              owner: root
              group: root
          services:
            sysvinit:
              httpd:
                enabled: 'true'
                ensureRunning: 'true'
              sendmail:
                enabled: 'false'
                ensureRunning: 'false'
    Properties:
      ImageId: !FindInMap 
        - AWSRegionArch2AMI
        - !Ref 'AWS::Region'
        - !FindInMap 
          - AWSInstanceType2Arch
          - !Ref InstanceType
          - Arch
      KeyName: !Ref KeyName
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
      - !Ref SecurityGroupServer
      SubnetId: !Ref SubnetId
      Tags:
        -
          Key: Name
          Value: !Sub ec2-wordpress-${Environment}
      UserData: !Base64 
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash
            - |
              yum update -y aws-cfn-bootstrap
            - '/opt/aws/bin/cfn-init -s '
            - !Ref 'AWS::StackId'
            - ' -r EC2Instance '
            - '--region '
            - !Ref 'AWS::Region'
            - |+

            - /opt/aws/bin/cfn-signal -e $? '
            - !Ref WaitHandle
            - |
              '
            - |
              # Setup correct file ownership
            - |
              chown -R apache:apache /var/www/html/wordpress
  WaitHandle:
    Type: 'AWS::CloudFormation::WaitConditionHandle'
  WaitCondition:
    Type: 'AWS::CloudFormation::WaitCondition'
    DependsOn: EC2Instance
    Properties:
      Handle: !Ref WaitHandle
      Timeout: '1200'

  EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref EC2Instance

Outputs:

  Ec2Id:
    Value: !Ref EC2Instance

  Ec2PublicId:
    Value: !GetAtt EC2Instance.PublicIp  